name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Site with Maven
        run: mvn -B site --file pom.xml

      - name: Zip Site
        run: |
          cd target/site
          zip -r ../../SortingMadnessDocumentation.zip ./

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a GitHub release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Upload assets
      - name: Upload WAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/SortingMadness.war
          asset_name: SortingMadness.war
          asset_content_type: application/java-archive

      - name: Upload Documentation
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/SortingMadnessDocumentation.zip
          asset_name: SortingMadnessDocumentation.zip
          asset_content_type: application/zip
